version: 1.0.{build}

image: Ubuntu1804
platform: x86
stack:
    matrix:
	    - stack: node 7
	    - stack: node 8
		- stack: node 9.6

install:
    - sh: npm install
build_script:
    - sh: npm run build
test_script:
    - sh: npm run test
