version: 1.0.{build}

image: Ubuntu1804
platform: x86
environment:
    matrix:
        - nodejs_version: 7
        - nodejs_version: 8
        - nodejs_version: 9.6

stack: node $env:nodejs_version

matrix:
    fast_finish: true

install:
    - sh: npm install
build_script:
    - sh: npm run build
test_script:
    - sh: npm run test
