version: 1.0.{build}

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "latest"

install:
    - ps: Install-Product node $env:nodejs_version x86
    - ps: npm install
build_script:
    - ps: npm run build
test_script:
    - ps: npm run test
